spring:
  profiles:
    active:
      - printer
      - dev
      - user

---
spring:
  profiles: dev
home:
  config:
    url: "http://localhost.com"
    port: "8080"
app:
  config:
    appconfig:
      instrument: "ir swap"

---
spring:
  profiles: user
home:
  config:
    port: "5555"
app:
  config:
    appconfig:
      username: "user1"
      instrument: "bonds"


